name: flutter_sticky_header
description: Flutter implementation of sticky headers as a sliver. Use it in a CustomScrollView. Forked by VeriFi.
version: 0.6.5

dependencies:
  flutter:
    sdk: flutter
  value_layout_builder: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sliver_tools: ^0.2.7

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.19.0"
